from __future__ import annotations

import json
import tempfile
import threading
import unittest
from pathlib import Path
from unittest import mock

from local_agent.config import AgentConfig
from local_agent.context import ContextSelector
from local_agent.impact import ChangeImpactAnalyzer
from local_agent.models import ChangeImpact, CommandSpec, FileOperation, FailureAnalysis, Plan, ProjectContext, ProviderCapability, ReviewResult, ValidationCommand, ValidationPlan
from local_agent.orchestrator import Orchestrator
from local_agent.providers import AIProvider, _bounded_context
from local_agent.repository import RepositoryIntelligence
from local_agent.storage import JsonFileStorage
from local_agent.validation import ValidationIntelligence


class CapturingProvider(AIProvider):
    def __init__(self):
        self.plan_context = None
        self.serialized_context = None

    @property
    def capabilities(self) -> set[ProviderCapability]:
        return {
            ProviderCapability.PLANNING, ProviderCapability.IMPLEMENTATION,
            ProviderCapability.REPAIR, ProviderCapability.REVIEW,
        }

    def generate_plan(self, task: str, context: ProjectContext) -> Plan:
        self.plan_context = context
        self.serialized_context = _bounded_context(context, 30000, 20, 10000)
        return Plan(objective=task, steps=["Use the impact analysis and validation plan to guide the change."])

    def generate_code(self, task: str, plan: Plan, context: ProjectContext, failure: FailureAnalysis | None = None, review: ReviewResult | None = None) -> list[FileOperation]:
        return []

    def analyze_failure(self, execution, diff, context, plan):
        return FailureAnalysis("deterministic test failure", [], "inspect the failing test")

    def review_changes(self, task, plan, diff, context):
        return ReviewResult("APPROVED", "No changes were generated by the fake provider.")


class Phase38Tests(unittest.TestCase):
    def _repository(self) -> Path:
        root = Path(tempfile.mkdtemp())
        # Python project setup
        (root / "pyproject.toml").write_text("[project]\nname='my-python-app'\n[tool.ruff]\nline-length=88\n", encoding="utf-8")
        (root / "requirements.txt").write_text("pytest\nmypy\n", encoding="utf-8")
        (root / "src").mkdir(parents=True)
        (root / "src" / "app.py").write_text("def hello(): return 'world'\n", encoding="utf-8")
        (root / "src" / "auth.py").write_text("def login(): pass\n", encoding="utf-8")
        (root / "tests").mkdir(parents=True)
        (root / "tests" / "test_app.py").write_text("import pytest\nfrom src.app import hello\ndef test_hello(): assert hello() == 'world'\n", encoding="utf-8")
        (root / "tests" / "test_auth.py").write_text("import pytest\nfrom src.auth import login\ndef test_login(): assert login() is None\n", encoding="utf-8")
        (root / "mypy.ini").write_text("[mypy]\n", encoding="utf-8")

        # JS/TS project setup
        (root / "package.json").write_text(json.dumps({
            "name": "my-js-app",
            "scripts": {
                "test": "vitest",
                "test:unit": "vitest run --dir src",
                "test:e2e": "cypress run",
                "typecheck": "tsc --noEmit",
                "build": "vite build",
                "lint": "eslint .",
                "format": "prettier --write .",
                "db:reset": "npx prisma migrate reset --force", # Destructive
                "deploy": "firebase deploy", # Destructive
            },
            "devDependencies": {
                "vitest": "^1.0.0",
                "cypress": "^10.0.0",
                "typescript": "^5.0.0",
                "vite": "^4.0.0",
                "eslint": "^8.0.0",
                "prettier": "^3.0.0",
                "prisma": "^5.0.0",
                "firebase-tools": "^11.0.0"
            }
        }), encoding="utf-8")
        (root / "tsconfig.json").write_text("{}", encoding="utf-8")
        (root / "src" / "components").mkdir(parents=True)
        (root / "src" / "components" / "Button.tsx").write_text("export function Button() { return <button>Click</button>; }\n", encoding="utf-8")
        (root / "src" / "pages").mkdir(parents=True)
        (root / "src" / "pages" / "AboutPage.tsx").write_text("export function AboutPage() { return <div>About</div>; }\n", encoding="utf-8")
        (root / "src" / "app").mkdir(parents=True)
        (root / "src" / "app" / "router.tsx").write_text("import { AboutPage } from '../pages/AboutPage';\n", encoding="utf-8")

        return root

    def _get_repo_map(self, root: Path) -> RepositoryMap:
        return RepositoryIntelligence(root).scan().repository_map

    def _get_change_impact(self, root: Path, task: str) -> ChangeImpact:
        context = RepositoryIntelligence(root).scan()
        ContextSelector(root, max_files=12).select(task, context)
        return ChangeImpactAnalyzer(root).analyze(task, context)

    def test_js_command_discovery(self):
        root = self._repository()
        repo_map = self._get_repo_map(root)
        validation_intelligence = ValidationIntelligence(root)
        commands = validation_intelligence.discover_commands(repo_map)
        command_names = {cmd.name for cmd in commands}
        self.assertIn("test", command_names)
        self.assertIn("test:unit", command_names)
        self.assertIn("test:e2e", command_names)
        self.assertIn("typecheck", command_names)
        self.assertIn("build", command_names)
        self.assertIn("lint", command_names)
        self.assertIn("format", command_names)
        self.assertIn("db:reset", command_names)
        self.assertIn("deploy", command_names)

        test_cmd = next(cmd for cmd in commands if cmd.name == "test")
        self.assertEqual(test_cmd.category, "unit_test")
        self.assertEqual(test_cmd.risk, "low")
        e2e_cmd = next(cmd for cmd in commands if cmd.name == "test:e2e")
        self.assertEqual(e2e_cmd.category, "e2e_test")
        self.assertEqual(e2e_cmd.risk, "medium")
        db_reset_cmd = next(cmd for cmd in commands if cmd.name == "db:reset")
        self.assertEqual(db_reset_cmd.category, "destructive")
        self.assertEqual(db_reset_cmd.risk, "high")
        self.assertTrue(db_reset_cmd.destructive)

    def test_python_command_discovery(self):
        root = self._repository()
        repo_map = self._get_repo_map(root)
        validation_intelligence = ValidationIntelligence(root)
        commands = validation_intelligence.discover_commands(repo_map)
        command_names = {cmd.name for cmd in commands}
        self.assertIn("unittest", command_names)
        self.assertIn("pytest", command_names)
        self.assertIn("mypy", command_names)
        self.assertIn("ruff", command_names)
        self.assertIn("compileall", command_names)

        pytest_cmd = next(cmd for cmd in commands if cmd.name == "pytest")
        self.assertEqual(pytest_cmd.category, "unit_test")
        self.assertEqual(pytest_cmd.risk, "low")
        ruff_cmd = next(cmd for cmd in commands if cmd.name == "ruff")
        self.assertEqual(ruff_cmd.category, "lint")
        self.assertEqual(ruff_cmd.risk, "low")

    def test_task_aware_validation_selection_add_page(self):
        root = self._repository()
        repo_map = self._get_repo_map(root)
        change_impact = self._get_change_impact(root, "Add an About page and link it in navigation.")
        validation_intelligence = ValidationIntelligence(root)
        discovered_commands = validation_intelligence.discover_commands(repo_map)
        validation_plan = validation_intelligence.select_commands("Add an About page and link it in navigation.", change_impact, discovered_commands)

        primary_names = {cmd.name for cmd in validation_plan.primary_commands}
        secondary_names = {cmd.name for cmd in validation_plan.secondary_commands}
        skipped_names = {cmd.name for cmd in validation_plan.skipped_commands}

        self.assertIn("typecheck", primary_names) # tsc --noEmit
        self.assertIn("lint", primary_names) # eslint
        self.assertIn("test", primary_names) # vitest
        self.assertIn("build", primary_names) # vite build
        self.assertIn("test:e2e", secondary_names) # cypress run, due to navigation
        self.assertIn("db:reset", skipped_names)
        self.assertEqual(validation_plan.risk_level, "high") # Because destructive commands were discovered

    def test_task_aware_validation_selection_fix_auth(self):
        root = self._repository()
        repo_map = self._get_repo_map(root)
        change_impact = self._get_change_impact(root, "Fix login authentication.")
        validation_intelligence = ValidationIntelligence(root)
        discovered_commands = validation_intelligence.discover_commands(repo_map)
        validation_plan = validation_intelligence.select_commands("Fix login authentication.", change_impact, discovered_commands)

        primary_names = {cmd.name for cmd in validation_plan.primary_commands}
        secondary_names = {cmd.name for cmd in validation_plan.secondary_commands}

        self.assertIn("pytest", primary_names) # Specific auth test
        self.assertIn("typecheck", primary_names)
        self.assertIn("lint", primary_names)
        self.assertIn("test", primary_names) # General unit tests
        self.assertIn("build", primary_names)
        self.assertIn("test:e2e", secondary_names) # E2E might be relevant for auth flow

    def test_task_aware_validation_selection_refactor_component(self):
        root = self._repository()
        repo_map = self._get_repo_map(root)
        change_impact = self._get_change_impact(root, "Refactor shared Button component.")
        validation_intelligence = ValidationIntelligence(root)
        discovered_commands = validation_intelligence.discover_commands(repo_map)
        validation_plan = validation_intelligence.select_commands("Refactor shared Button component.", change_impact, discovered_commands)

        primary_names = {cmd.name for cmd in validation_plan.primary_commands}
        secondary_names = {cmd.name for cmd in validation_plan.secondary_commands}

        self.assertIn("typecheck", primary_names)
        self.assertIn("lint", primary_names)
        self.assertIn("test", primary_names) # General unit tests
        self.assertIn("build", primary_names)
        self.assertNotIn("test:e2e", primary_names) # E2E less likely for isolated component refactor

    def test_orchestrator_passes_validation_plan_to_provider_and_report(self):
        root = self._repository()
        provider = CapturingProvider()
        config = AgentConfig.from_environment(root, max_iterations=1)

        storage = JsonFileStorage(root / ".agent_data")
        orchestrator = Orchestrator(config, storage, None, threading.Lock(), threading.Lock())
        from local_agent.models import ExecutionResult
        with mock.patch("local_agent.orchestrator.build_provider", return_value=provider), \
             mock.patch.object(orchestrator.runner, "run", return_value=ExecutionResult("mock", 0)):
            report = orchestrator.run("Add an About page and link it in navigation.")

        self.assertTrue(report.completed)
        self.assertIsNotNone(report.impact)
        self.assertIsNotNone(report.validation_plan)

        # Verify validation plan in report
        self.assertEqual(report.validation_plan.risk_level, "high") # Due to destructive commands discovered
        self.assertGreater(len(report.validation_plan.primary_commands), 0)
        self.assertGreater(len(report.validation_plan.skipped_commands), 0)

        # Verify validation plan in provider context
        stored_validation_plan = provider.plan_context.metadata["validation_plan"]
        self.assertIsNotNone(stored_validation_plan)
        self.assertEqual(stored_validation_plan["risk_level"], "high")
        self.assertGreater(len(stored_validation_plan["primary_commands"]), 0)

        # Verify validation plan in serialized context
        serialized_validation_plan = provider.serialized_context["metadata"]["validation_plan"]
        self.assertIsNotNone(serialized_validation_plan)
        self.assertEqual(serialized_validation_plan["risk_level"], "high")
        self.assertGreater(len(serialized_validation_plan["primary_commands"]), 0)

    def test_orchestrator_executes_primary_validation_commands(self):
        root = self._repository()
        # Create a mock validation command that always passes
        (root / "pass_test.py").write_text("import sys; sys.exit(0)", encoding="utf-8")
        # Create a mock validation command that always fails
        (root / "fail_test.py").write_text("import sys; sys.exit(1)", encoding="utf-8")

        # Override ValidationIntelligence to return specific commands
        class MockValidationIntelligence(ValidationIntelligence):
            def discover_commands(self, repo_map: RepositoryMap) -> list[ValidationCommand]:
                return [
                    ValidationCommand(name="pass_test", command=("python", "pass_test.py"), category="unit_test", confidence=1.0, reason="mock pass", risk="low"),
                    ValidationCommand(name="fail_test", command=("python", "fail_test.py"), category="unit_test", confidence=1.0, reason="mock fail", risk="low"),
                    ValidationCommand(name="destructive_cmd", command=("rm", "-rf", "/"), category="destructive", confidence=1.0, reason="mock destructive", risk="high", destructive=True),
                ]
            def select_commands(self, task: str, change_impact: ChangeImpact, discovered_commands: list[ValidationCommand]) -> ValidationPlan:
                return ValidationPlan(
                    commands=discovered_commands,
                    primary_commands=[CommandSpec("pass_test", ("python", "pass_test.py"), "mock pass", "unit_test", "low", False)],
                    secondary_commands=[CommandSpec("fail_test", ("python", "fail_test.py"), "mock fail", "unit_test", "low", False)],
                    skipped_commands=[CommandSpec("destructive_cmd", ("rm", "-rf", "/"), "mock destructive", "destructive", "high", True)],
                    reasons=["mock plan"],
                    risk_level="low",
                )

        with mock.patch('local_agent.orchestrator.ValidationIntelligence', new=MockValidationIntelligence):
            provider = CapturingProvider()
            config = AgentConfig.from_environment(root, max_iterations=1)
            storage = JsonFileStorage(root / ".agent_data")
            orchestrator = Orchestrator(config, storage, None, threading.Lock(), threading.Lock())
            with mock.patch("local_agent.orchestrator.build_provider", return_value=provider):
                report = orchestrator.run("Test task.")

            self.assertTrue(report.completed)
            self.assertEqual(len(report.executions), 1)
            self.assertEqual(report.executions[0].command, "python pass_test.py")
            self.assertTrue(report.executions[0].succeeded)
            self.assertFalse(any("fail_test.py" in exec.command for exec in report.executions))
            self.assertFalse(any("destructive_cmd" in exec.command for exec in report.executions))

    def test_orchestrator_stops_on_validation_failure(self):
        root = self._repository()
        (root / "fail_test.py").write_text("import sys; sys.exit(1)", encoding="utf-8")

        class MockValidationIntelligence(ValidationIntelligence):
            def discover_commands(self, repo_map: RepositoryMap) -> list[ValidationCommand]:
                return [
                    ValidationCommand(name="fail_test", command=("python", "fail_test.py"), category="unit_test", confidence=1.0, reason="mock fail", risk="low"),
                ]
            def select_commands(self, task: str, change_impact: ChangeImpact, discovered_commands: list[ValidationCommand]) -> ValidationPlan:
                return ValidationPlan(
                    commands=discovered_commands,
                    primary_commands=[CommandSpec("fail_test", ("python", "fail_test.py"), "mock fail", "unit_test", "low", False)],
                    secondary_commands=[],
                    skipped_commands=[],
                    reasons=["mock plan"],
                    risk_level="low",
                )

        with mock.patch('local_agent.orchestrator.ValidationIntelligence', new=MockValidationIntelligence):
            provider = CapturingProvider()
            config = AgentConfig.from_environment(root, max_iterations=1)
            storage = JsonFileStorage(root / ".agent_data")
            orchestrator = Orchestrator(config, storage, None, threading.Lock(), threading.Lock())
            with mock.patch("local_agent.orchestrator.build_provider", return_value=provider):
                report = orchestrator.run("Test task.")

            self.assertFalse(report.completed) # Should not be completed due to failure
            self.assertEqual(len(report.executions), 1)
            self.assertEqual(report.executions[0].command, "python fail_test.py")
            self.assertFalse(report.executions[0].succeeded)
            self.assertEqual(len(report.failures), 1)
            self.assertEqual(report.failures[0].probable_root_cause, "deterministic test failure") # From CapturingProvider.analyze_failure

    def test_validation_plan_serialization(self):
        root = self._repository()
        repo_map = self._get_repo_map(root)
        change_impact = self._get_change_impact(root, "Add an About page.")
        validation_intelligence = ValidationIntelligence(root)
        discovered_commands = validation_intelligence.discover_commands(repo_map)
        validation_plan = validation_intelligence.select_commands("Add an About page.", change_impact, discovered_commands)

        serialized = validation_plan.to_dict()
        self.assertIn("risk_level", serialized)
        self.assertIn("primary_commands", serialized)
        self.assertIsInstance(serialized["primary_commands"][0], dict) # Should be dict from CommandSpec.to_dict()
        self.assertIn("command", serialized["primary_commands"][0])
        self.assertIn("category", serialized["commands"][0]) # Full ValidationCommand should be serialized