from __future__ import annotations

import datetime
import json
import os
import re
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

from .models import PullRequestInfo, Task

if TYPE_CHECKING:
    from .config import AgentConfig
    from .git import GitIntegration


class RemoteError(Exception):
    pass


class RemoteProvider(ABC):
    @abstractmethod
    def create_pull_request(self, task: Task, branch_name: str) -> PullRequestInfo:
        pass

    @abstractmethod
    def find_pull_request_for_branch(self, branch_name: str) -> PullRequestInfo | None:
        pass


class GitHubProvider(RemoteProvider):
    def __init__(self, config: AgentConfig, git: GitIntegration):
        self.config = config
        self.git = git
        self.token = os.environ.get("GITHUB_TOKEN")
        if not self.token:
            raise RemoteError("GITHUB_TOKEN environment variable is not set.")

        remote_url = self.git.get_remote_url(self.config.git_default_remote)
        if not remote_url:
            raise RemoteError(f"Could not determine remote URL for '{self.config.git_default_remote}'.")

        match = re.search(r"github\.com[/:]([\w.-]+)/([\w.-]+?)(?:\.git)?$", remote_url)
        if not match:
            raise RemoteError(f"Could not parse owner/repo from remote URL: {remote_url}")
        self.owner, self.repo = match.groups()
        self.api_base_url = "https://api.github.com"

    def _api_call(self, method: str, endpoint: str, data: dict | None = None) -> dict | list:
        url = f"{self.api_base_url}{endpoint}"
        body = json.dumps(data).encode("utf-8") if data is not None else None
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
        }
        request = urllib.request.Request(url, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="ignore")
            raise RemoteError(f"GitHub API request failed ({e.code}): {error_body}") from e
        except (urllib.error.URLError, TimeoutError) as e:
            raise RemoteError(f"Network error during GitHub API request: {e}") from e

    def find_pull_request_for_branch(self, branch_name: str) -> PullRequestInfo | None:
        head_filter = f"{self.owner}:{branch_name}"
        prs = self._api_call("GET", f"/repos/{self.owner}/{self.repo}/pulls?head={head_filter}&state=open")
        if not isinstance(prs, list) or not prs:
            return None
        
        pr_data = prs[0]
        return PullRequestInfo(
            provider="github",
            pr_id=str(pr_data["number"]),
            url=pr_data["html_url"],
            status=pr_data["state"],
            created_at=_parse_iso_datetime(pr_data["created_at"]),
        )

    def create_pull_request(self, task: Task, branch_name: str) -> PullRequestInfo:
        default_branch = self.git.get_current_branch() # A simplification; should ideally get repo's default branch
        
        data = {
            "title": f"feat: {task.objective}",
            "head": branch_name,
            "base": default_branch,
            "body": f"This PR was automatically generated by the DungX AI Coding Agent to complete the following task:\n\n**Objective:** {task.objective}\n**Task ID:** {task.task_id}",
            "draft": False,
        }
        pr_data = self._api_call("POST", f"/repos/{self.owner}/{self.repo}/pulls", data=data)
        if not isinstance(pr_data, dict):
            raise RemoteError("Invalid response from GitHub API when creating PR.")

        return PullRequestInfo(
            provider="github",
            pr_id=str(pr_data["number"]),
            url=pr_data["html_url"],
            status=pr_data["state"],
            created_at=_parse_iso_datetime(pr_data["created_at"]),
        )


def _parse_iso_datetime(val: str) -> datetime.datetime:
    if val.endswith("+00:00Z"):
        val = val[:-1]
    elif val.endswith("Z"):
        val = val[:-1] + "+00:00"
    return datetime.datetime.fromisoformat(val)


def build_remote_provider(config: AgentConfig) -> RemoteProvider | None:
    from .git import GitIntegration

    if config.git_hosting_provider == "github":
        try:
            git = GitIntegration(config.project)
            if not git.is_repository():
                return None
            return GitHubProvider(config, git)
        except RemoteError as e:
            # Log this warning but don't crash the whole agent if git/remote is misconfigured
            print(f"Warning: Could not initialize GitHub provider: {e}")
            return None
    return None